name: eqs-gb-norm-of-b
channels:
  - conda-forge
  - defaults
dependencies:
  # Should be on every project
  - python==3.10.*
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - black
  # For building latex documents
  - make
  - tectonic
  # Project specific dependencies
  - pandas
  - xarray
  - netcdf4
  - pygmt
  - pyproj
  # Fatiando
  - pooch
  - verde
  - harmonica
  - choclo
  - pip
  - pip:
      - git+https://github.com/fatiando/harmonica
